### ISSUE TITLE
Cancelling a self-hosted mod update causes a manifest error

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/mod-loader-common#14]
![image](https://user-images.githubusercontent.com/23312549/188298204-0021920c-10af-4e00-973c-50a5ab9a4c56.png)
![image](https://user-images.githubusercontent.com/23312549/188298261-14e4e91b-2844-4a36-8715-4330a1ea2896.png)

Clicking Retry produces the error below.
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Start may not be called on a task that has completed.
   at System.Threading.Tasks.Task.Start(TaskScheduler scheduler)
   at ModManagerCommon.Forms.ModDownloadDialog.OnShown(Object sender, EventArgs eventArgs) in C:\Programs\sadx-mod-loader\mod-loader-common\ModManagerCommon\Forms\ModDownloadDialog.cs:line 93
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

**Comment by PiKeyAr** [comment]
Fixed in https://github.com/X-Hax/mod-manager-common/commit/b6f4782fd47909ff25ac250d15790ae640d16f5d
